### ISSUE TITLE
new distribution doesn't work

### ISSUE THREAD

**Issue by cywtum** [HenningScheufler/multiDimAMR#1]
I have tested the solver with damBreakWithObstacle. But after the new distribution, the simulation just crashed. Could you give me some hints?

**Comment by HenningScheufler** [comment]
Could you share the case and tell me your openfoam version so i can reproduce it?

**Comment by cywtum** [comment]
Thanks for your reply. Actually I use the damBreakWithObstacles in your tutorials but with mesh refinement (160*160*160) and 28 processors. I attached the case file and the output. Have you tested this case with 4 processors?
[damBreakWithObstacles.zip](https://github.com/HenningScheufler/multiDimAMR/files/5672084/damBreakWithObstacles.zip)

**Comment by HenningScheufler** [comment]
the bug is in interIsoFoam I will open a bug report on develop openfoam:

https://develop.openfoam.com/Development/openfoam/-/issues/1955

**Comment by cywtum** [comment]
Thanks for your help. Does this bug exist in your interFlow solver?

**Comment by HenningScheufler** [comment]
sadly no but i'm on it

**Comment by HenningScheufler** [comment]
the master of the VoFLibrary (https://github.com/DLR-RY/VoFLibrary)  works with the dambreakWithObstacle tutorial just change the application name in the controlDict
