### ISSUE TITLE
interFoam crashes after load balancing

### ISSUE THREAD

**Issue by maximilian-tech** [HenningScheufler/multiDimAMR#2]
I am simulating a water jet using  your library. If I enable loadbalancing in constant/dynamicMeshDict, interFoam crashes after  successful loadbalancing (3 Cores).
I am using OpenFOAM v2006. The case is attached.
Thanks for your help!
[jet_interFoam.zip](https://github.com/HenningScheufler/multiDimAMR/files/5927486/jet_interFoam.zip)

**Comment by HenningScheufler** [comment]
Thanks for the test case the really helps.
I could reproduce the problem and modified the case that it runs with 5b84afb

[jet_interFoam.zip](https://github.com/HenningScheufler/multiDimAMR/files/5927683/jet_interFoam.zip)

The error is in function1 tablebase with a fixedValue boundary condition the case works (see attached file). Looking into it

**Comment by HenningScheufler** [comment]
this should be fixed in version 2012
