### ISSUE TITLE
Unable to read cellLevel from snappy-hex-mesh utility mesh

### ISSUE THREAD

**Issue by Bumble-7** [HenningScheufler/multiDimAMR#6]
Dear Authors,
I have compiled the multi-dim-AMR and trying to run the simulation having multi regions. I have referred to the tutorials present in the following directory.
TwoPhaseFlow/modules/multiDimAMR/tutorials
The initial refined cells are further refined even though the cellLevel variable is correctly present in the initial time step.

No tutorial is using snappy hex mesh utility, but it has the refinemeshDict which is not being called. So could you please tell me if the snappy hex mesh is compatible? If not, any other method to refine the initial mesh?

Thank you

**Comment by Bumble-7** [comment]
I figured out that the split-region utility which creates the files for different regions is not creating the label-list file for different regions. Currently, I am adding those files manually. If that is done, the cell levels are read from the initial condition. Let me know if there is a direct way to do this. 

Thank you

**Comment by Bumble-7** [comment]
Could you please provide a tutorial consisting of the multi-regions and using snappy hex mesh? Even though for single phase dynamicMeshDict is successful, for multi-region I am facing some issues. It is unable to refine the cells which are near the solid region. As the snappyhexmesh is used in most cases, providing such a tutorial might be really helpful. 

Thank you

**Comment by HenningScheufler** [comment]
This Library only works with hex cells or wedge (2D axsym) so it will not work with snappy
